"""create pass secure column

Revision ID: 701fbd1c7a8f
Revises: 47fe3bc760dd
Create Date: 2021-08-16 23:31:43.815754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701fbd1c7a8f'
down_revision = '47fe3bc760dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
